services:
  db:
    image: postgres:17.5-alpine
    volumes:
      - .docker/.volumes/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - .docker/.volumes/redis/data:/data

  app:
    build:
      context: .
      dockerfile: .docker/dev.Dockerfile
    restart: always
    volumes:
      - .:/app/
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
      dockerfile: .docker/dev.Dockerfile
    restart: always
    volumes:
      - .:/app/
    env_file: .env
    command: celery -A config worker --loglevel=info
    depends_on:
      - app
      - redis
